padl/transforms.py
Device is properly propagated to pd_forward, etc.
=> Device fix

padl/dumptools/symfinder.py, padl/dumptools/var2mod.py, padl/transforms.py, tests/unittests/test_transforms.py, tests/unittests/test_wrap.py
@wuhu I modified `test_function_a` to use a variable rename `np = transform(np)` and it looks like the test hangs indefinitely when trying to save the transform. Could you take a look at this when you have the chance?
=> Added tests for zip saving and variable renaming

.github/ISSUE_TEMPLATE/documentation.md, notebooks/01_MNIST_using_padl.ipynb
Update to MNIST notebook to use torchvision dataset instead of kaggle dataset
Fixes [#\<issue_number>](https://github.com/lf1-io/padl/issues/257)
=> fix to notebook

padl/transforms.py, tests/unittests/test_transforms.py
Fixes #264 #266
Implemented postprocess logic to follow aleph.
=> Upating post logic to follow aleph

padl/dumptools/inspector.py, padl/wrap.py
=> Bug double lambda

padl/transforms.py
Small update to infer_apply to return namedtuple, same behavior as eval_apply and train_apply
=> Small update to infer_apply

padl/transforms.py
printing compositions of single input functions was failing - fixing that
=> hotfix - printing compositions of single input functions was failing

requirements-docs.txt
Added requirement for building docs
=> Updated requirements for docs

tests/unittests/test_transforms.py
=> tests for new split

padl/transforms.py, tests/unittests/test_transforms.py
Fixes #304 by grouping stages (preprocess, forward and postprocess) of Parallel and Rollout.
=> 304 grouped split

README.md
=> Add twitter badge to REAME

.github/workflows/actions.yml
--doctest-modules accidentally added. Will be added once Issue #318 is resolved
=> Remove --doctest-modules

notebooks/02_nlp_example.ipynb
Needed to convert tuple to list to fix bug in `train_model`.
=> Update NLP notebook example

README.md
Add badge to show tests passing from github actions
=> Add badge for Tests

RELEASE.md
=> release process description

padl/transforms.py, tests/unittests/test_transforms.py
=> Name the splits of named transforms.

docs/src/usage.md, docs/src/usage/debugging_your_transforms.md, docs/unstable/_static/pygments.css, padl/transforms.py, padl/util_transforms.py, padl/utils.py, tests/unittests/test_transforms.py
=> Debugger 4

docs/0.1.6/README.html, docs/0.1.6/advanced.html, docs/0.1.6/advanced/saving.html, docs/0.1.6/apidocs/padl.dumptools.ast_utils.html, docs/0.1.6/genindex.html, docs/0.1.6/index.html, docs/0.1.6/modules.html, docs/0.1.6/search.html, docs/0.1.6/usage.html, docs/0.1.6/usage/apply.html, docs/0.1.6/usage/combining_transforms.html, docs/0.1.6/usage/creating_transforms.html, docs/0.1.6/usage/extras.html, docs/0.1.6/usage/print_slice.html, docs/0.1.6/usage/pytorch.html, docs/0.1.6/usage/saving.html, docs/0.1.6/usage/stages.html, docs/0.1.6/usage/transform.html
=> Updated versions script in html files of docs 0.1.6

padl/transforms.py, padl/utils.py
Fixes #368 
```python
@transform
class Generator:
def __init__(self, channel_number=96, 
network_depth=5,
in_channels=50, 
convolution_type='regular', 
image_channels=3):
self.channel_number = channel_number
self.network_depth = network_depth
self.convolution_type = convolution_type
self.image_channels = image_channels
def __call__(self, input):
return input
f = identity - 'f'
gen = Generator(channel_number=96, 
network_depth=5,
in_channels=50, 
convolution_type='regular', 
image_channels=3)
```
```
comp = (
f
>> batch
>> f
>> gen
)
Compose - "comp":
│
▼ args
0: Identity(-?-)                                                                                              
│
▼ args
1: Batchify(dim=0)                                                                                            
│ …
```
=> 368 print statement limited column

padl/transforms.py, tests/unittests/test_transforms.py
=> 390 save id

padl/wrap.py
=> Fix lambda wrapping edge case.

padl/dumptools/sourceget.py, padl/transforms.py
=> 387 save loaded transforms

padl/transforms.py, tests/unittests/test_transforms.py
=> 395 Pipeline getiem recursively search for pd_name

padl/transforms.py, padl/util_transforms.py, tests/unittests/test_transforms.py
Added the missing logic for unbatchify.
Fixes: https://github.com/lf1-io/padl/issues/400
=> 400 identities with map rollout

padl/transforms.py, tests/unittests/test_transforms.py
Allows Pipeline to have `unbatchify` without `batchify`
=> Soften Unbatchify Assertion

notebooks/01_MNIST_using_padl.ipynb
=> mnist update

padl/dumptools/inspector.py, padl/wrap.py
=> Fix modulewrap

.github/workflows/build_docs.yml
=> Build docs only on merge to master (not for every PR).

padl/transforms.py
Fixes #28 by adding an keyword argument ignore_post on the train_apply method.
=> Add an keyword argument ignore_post on the train_apply method.
